<h1><?php // echo $this->titulo?></h1>
<?php
$form = $this->form;
$form->prepare();
$form->setAttributes(array(
    'action' => $this->url.'/formulario/formulario/registro'
));
// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>
<?php
if(!empty($this->id))
{
    ?>
    <p style="color: green;">El registro se ingreso correctamente</p>
    <?php
}
?>
        <div id="page-wrapper2">
            <div class="row">
                <div class="col-lg-12">
                  <!--  <h1 class="page-header">Registro</h1> -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <b>Registro</b>
                        </div>
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-lg-6">
                                  




<div class="form-group">
<?php
   /* $name = $form->get('profilename');
    echo $formLabel->openTag().$name->getOption('label')." ";
    echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    echo $this->formInput($name); */

echo $this->formRow($form->get('profilename'));

?>
</div>


<div class="form-group">

<?php
    /*$email = $form->get('email');
    echo $formLabel->openTag().$email->getOption('label')." ";
    echo $this->formElementErrors($email);
    echo $formLabel->closeTag();
    echo $this->formInput($email);*/

echo $this->formRow($form->get('email'));

?>
</div>


<div class="form-group">
<?php
   /* $pass = $form->get('pass');
    echo $formLabel->openTag().$pass->getOption('label')." ";
    echo $this->formElementErrors($pass);
    echo $formLabel->closeTag();
    echo $this->formInput($pass);  */

echo $this->formRow($form->get('pass'));


?>
</div>

<div class="form-group">
    <?php

    $gender = $form->get('genero');
    echo $formLabel->openTag() . $gender->getLabel();
    echo $formLabel->closeTag();
    echo $this->formRadio($gender);
    echo $this->formElementErrors($gender);

    ?>
</div>


<div class="form-group">
    <?php
    $lenguaje = $form->get('lenguaje');
    echo $formLabel->openTag() . $lenguaje->getLabel();
    echo $formLabel->closeTag();
    echo $this->formSelect($lenguaje);
    echo $this->formElementErrors($lenguaje);
    ?>
</div>

<div class="form-group">
    <?php
    $lenguaje = $form->get('pais');
    echo $formLabel->openTag() . $lenguaje->getLabel();
    echo $formLabel->closeTag();
    echo $this->formSelect($lenguaje);
    echo $this->formElementErrors($lenguaje);
    ?>
</div>

<div class="form-group">
    <?php
    $preferencias = $form->get('preferencias');
    echo $formLabel->openTag() . $preferencias->getLabel();
    echo $formLabel->closeTag();
    echo $this->formMultiCheckbox($preferencias);
    echo $this->formElementErrors($preferencias);
    ?>
</div>

<div class="form-group">
    <?php
    $condiciones = $form->get('condiciones');
    echo $formLabel->openTag() . $condiciones->getLabel();
    echo $formLabel->closeTag();
    echo $this->formCheckbox($condiciones);
    echo $this->formElementErrors($condiciones);
    ?>
</div>

<div class="form-group"> 
<?php
    	/*$fileElement = $form->get('fileupload');
         echo $this->formLabel($fileElement);
         echo $this->formFile($fileElement);
         echo $this->formElementErrors($fileElement);  */

echo $this->formRow($form->get('fileupload'));


?> 
</div>



<?php echo $this->formHidden($form->get('oculto')) ?>

<?php echo $this->formElement($form->get('send')) ?>

<?php echo $this->form()->closeTag() ?>


                            </div>
                            <!-- /.row (nested) -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

   