<h1><?php echo $this->titulo;?></h1>
<p>
    <a href="<?php echo $this->basePath() ?>/formulario/formulario/index">Volver Atr&aacute;s</a>
</p>
<p>
    <?php


    echo $datos["id"]."<br>";
 echo $datos["nombre"]."<br>";
 echo $datos["correo"]."<br>";
 echo $datos["password"]."<br>";

 echo $datos["genero"]."<br>";
 echo $datos["idioma"]."<br>";
 echo $datos["pais"]."<br>";
 echo $datos["preferencias"]."<br>";
 echo $datos["nombre_archivo"]."<br>";
 echo $datos["acepta_condiciones"]."<br>";



    ?>




</p>