<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Formulario\Module'                        => __DIR__ . '/Module.php',
    'Formulario\Controller\IndexController' => __DIR__ . '/src/Formulario/Controller/IndexController.php',
    'Formulario\Framework\TestCase'        => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'Formulario\SampleTest'                => __DIR__ . '/tests/Formulario/SampleTest.php',
);